# An object bucket provider that binds bucket claims to an 
# existing (brownfield) bucket called "photos"
# for every object bucket claim, and deletes the bucket 
# when the object bucket claim is deleted
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hyperstore-photo-bucket
provisioner: aws-s3.io/bucket
parameters:
  region: reg-1
  secretName: s3-bucket-owner
  secretNamespace: s3-provisioner
  s3Endpoint: http://s3-reg-1.landemo1.cloudian.eu
  iamEndpoint: http://iam.landemo1.cloudian.eu:16080
  bucketName: photos # the existing bucket claims will attach to
