# Deploy the s3 provisioner
apiVersion: v1
kind: Namespace
metadata:
  name: s3-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hs-s3-provisioner-account
  namespace: s3-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hs-s3-provisioner-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - objectbucket.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hs-s3-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: hs-s3-provisioner-account
    namespace: s3-provisioner
roleRef:
  kind: ClusterRole
  name: hs-s3-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-s3-provisioner-deployment
  namespace: s3-provisioner
  labels:
    app: hs-s3-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hs-s3-provisioner
  template:
    metadata:
      labels:
        app: hs-s3-provisioner
    spec:
      serviceAccountName: hs-s3-provisioner-account
      containers:
        - name: hs-s3-provisioner
          image: quay.io/cloudian/hs-s3-provisioner:dev0.0.6
      restartPolicy: Always
