# Deploy the s3 provisioner
apiVersion: v1
kind: Namespace
metadata:
  name: cloudian-s3-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudian-s3-operator-account
  namespace: cloudian-s3-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudian-s3-operator-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - objectbucket.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudian-s3-operator-binding
subjects:
  - kind: ServiceAccount
    name: cloudian-s3-operator-account
    namespace: cloudian-s3-operator
roleRef:
  kind: ClusterRole
  name: cloudian-s3-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudian-s3-operator-deployment
  namespace: cloudian-s3-operator
  labels:
    app: cloudian-s3-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudian-s3-operator
  template:
    metadata:
      labels:
        app: cloudian-s3-operator
    spec:
      serviceAccountName: cloudian-s3-operator-account
      containers:
        - name: cloudian-s3-operator
          image: quay.io/cloudian/cloudian-s3-operator:dev0.0.6
      restartPolicy: Always
