# AWS credentials used by the operator
# Should have permissions to create/delete buckets and IAM users
# You can also create these credientials using the CLI:
#  kubectl create secret -n s3-provisioner generic s3-bucket-owner --from-literal=AWS_ACCESS_KEY_ID=<access key> --from-literal=AWS_SECRET_ACCESS_KEY=<secret key> 
apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket-owner
  namespace: s3-provisioner
type: Opaque
data:
  AWS_ACCESS_KEY_ID: your_base64_encoded_key
  AWS_SECRET_ACCESS_KEY: your_base64_encoded_secret