apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket-owner
  namespace: s3-provisioner
type: Opaque
data:
  AWS_ACCESS_KEY_ID: your_base64_encoded_key
  AWS_SECRET_ACCESS_KEY: your_base64_encoded_secret
