# An object bucket provider that creates a unique bucket 
# for every object bucket claim, and deletes the bucket 
# when the object bucket claim is deleted
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hyperstore-temp-buckets
provisioner: aws-s3.io/bucket
parameters:
  region: reg-1
  secretName: s3-bucket-owner
  secretNamespace: s3-provisioner
  s3Endpoint: http://s3-reg-1.landemo1.cloudian.eu
  iamEndpoint: http://iam.landemo1.cloudian.eu:16080

  # Set storagePolicyId to create buckets with specified policy
  #storagePolicyId: <policy id>

  # Provide an IAM policy document to override the default IAM policy
  # of read+write access to the bucket.
  # Omit the "Resource" field - it will be set to only allow access to the claimed bucket
  # For example to set a bucket read-only, uncomment the following:
  #iamPolicy: |
  #  {
  #    "Version": "2012-10-17",
  #    "Statement": [{
  #            "Sid": "AllowAll",
  #            "Effect": "Allow",
  #            "Action": ["s3:HeadObject", "s3:ListBucket", "s3:GetObject"]
  #    }]
  #  }

# Delete bucket when object bucket claim is deleted
reclaimPolicy: Delete
