kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: s3-buckets
provisioner: hs-s3.io/bucket
parameters:
  region: region1
  disableSSL: "true"
  endpointUrl: s3-region1.cloudian.com
  secretName: s3-bucket-owner
  secretNamespace: s3-provisioner
reclaimPolicy: Delete
